sudo: required

branches:
  only:
    - master

language: generic

services:
  - docker

before_install:
  - sudo ./vm-setup.sh
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    fi

jobs:
  include:
    - stage: dpdk
      script: |
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk -e CONTAINER=dpdk image-fresh
              else
                make -f docker.mk -e CONTAINER=dpdk build-fresh
              fi
    - stage: sandbox
      script: |
              if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                make -f docker.mk -e CONTAINER=sandbox image-fresh
              else
                make -f docker.mk -e CONTAINER=sandbox build-fresh
              fi
