sudo: required

branches:
  only:
    - master

language: generic

services:
  - docker

before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    fi

jobs:
  include:
    - stage: dpdk
      script: |
              $(git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep dpdk/Dockerfile > /dev/null);
              BUILD_DPDK=$?
              if [ "$BUILD_DPDK" = "0" ]; then
                if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                  make -f docker.mk -e CONTAINER=dpdk image-fresh
                else
                  make -f docker.mk -e CONTAINER=dpdk build-fresh
                fi
              fi
    - stage: sandbox
      script: |
              $(git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep Dockerfile.sandbox > /dev/null);
              BUILD_SANDBOX=$?
              if [ "$BUILD_SANDBOX" = "0" ]; then
                if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
                  make -f docker.mk -e CONTAINER=sandbox image-fresh
                else
                  make -f docker.mk -e CONTAINER=sandbox build-fresh
                fi
              fi
